M48
; DRILL file {KiCad (6.0.5-0)} date 2022 June 21, Tuesday 10:58:09
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-06-21T10:58:09+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X-38.1Y38.1
X-38.1Y-38.1
X0.0Y0.0
X38.1Y38.1
X38.1Y-38.1
T0
M30
