M48
; DRILL file {KiCad (6.0.7-1)-1} date 2022 August 07, Sunday 12:30:05
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-08-07T12:30:05+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X-9.525Y-47.625
X0.0Y0.0
X56.261Y0.0
X58.039Y-28.575
T0
M30
