M48
; DRILL file {KiCad (6.0.4-0)} date 2022 March 28, Monday 14:14:26
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-28T14:14:26+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X-28.575Y-19.05
X-28.575Y-47.625
X28.575Y-19.05
X38.1Y-57.15
T0
M30
