M48
; DRILL file {KiCad (6.0.7-1)-1} date 2022 August 07, Sunday 12:28:20
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-08-07T12:28:20+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X-58.039Y-28.575
X-56.261Y0.0
X0.0Y0.0
X9.525Y-47.625
T0
M30
